class EmailRepository:

    def exists_by_message_id(self, gmail_message_id):
        ...

    def list_by_thread_id(self, gmail_thread_id) -> list:
        ...

    def list_by_application_id(self, application_id) -> list:
        ...

    def create(self, email):
        ...